"""Best-effort requirements.txt → pyproject.toml conversion for uv.

Many repositories ship only requirements.txt. uv wants a project definition, so
we synthesize a minimal one. This is lossy: pip-only options, editable installs
and bare VCS URLs are dropped, so a converted project may fail to sync or run.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

CANDIDATE_NAMES = (
    "requirements.txt",
    "requirements/requirements.txt",
    "requirements/base.txt",
    "requirements/prod.txt",
    "requirements-dev.txt",
)

GENERATED_MARKER = "# generated by uvdrop from requirements.txt"

_PEP508_NAME = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*")


@dataclass
class ConversionResult:
    pyproject: Path
    dependencies: list[str]
    skipped: list[str] = field(default_factory=list)
    sources: list[Path] = field(default_factory=list)


def find_requirements(root: Path) -> Path | None:
    """Locate a requirements file at the root or one level down."""
    root = root.resolve()
    for rel in CANDIDATE_NAMES:
        cand = root / rel
        if cand.is_file():
            return cand
    for child in sorted(p for p in root.iterdir() if p.is_dir() and not p.name.startswith(".")):
        for rel in CANDIDATE_NAMES:
            cand = child / rel
            if cand.is_file():
                return cand
    return None


def parse_requirements(path: Path, *, _seen: set[Path] | None = None) -> tuple[list[str], list[str]]:
    """Return (dependencies, skipped_lines). Follows -r includes."""
    seen = _seen if _seen is not None else set()
    path = path.resolve()
    if path in seen or not path.is_file():
        return [], []
    seen.add(path)

    deps: list[str] = []
    skipped: list[str] = []
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.split(" #", 1)[0].strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith(("-r ", "--requirement ")):
            nested = path.parent / line.split(None, 1)[1].strip()
            sub_deps, sub_skipped = parse_requirements(nested, _seen=seen)
            deps.extend(sub_deps)
            skipped.extend(sub_skipped)
            continue
        if line.startswith("-"):
            # -e ., --index-url, --extra-index-url, --hash, ...
            skipped.append(line)
            continue
        if "://" in line and "@" not in line.split("://", 1)[0]:
            # Bare VCS/URL requirement is not a valid PEP 508 dependency
            skipped.append(line)
            continue
        if not _PEP508_NAME.match(line):
            skipped.append(line)
            continue
        deps.append(line)

    out: list[str] = []
    seen_names: set[str] = set()
    for d in deps:
        m = _PEP508_NAME.match(d)
        key = m.group(0).lower().replace("_", "-") if m else d.lower()
        if key in seen_names:
            continue
        seen_names.add(key)
        out.append(d)
    return out, skipped


def _project_name(project_dir: Path) -> str:
    name = re.sub(r"[^a-z0-9._-]+", "-", project_dir.name.lower()).strip("-._")
    return name or "converted-app"


def _detect_requires_python(project_dir: Path) -> str:
    pinned = project_dir / ".python-version"
    if pinned.is_file():
        text = pinned.read_text(encoding="utf-8", errors="replace").strip()
        m = re.search(r"(\d+\.\d+)", text)
        if m:
            return f">={m.group(1)}"
    return ">=3.9"


def convert_to_pyproject(requirements: Path, project_dir: Path | None = None) -> ConversionResult:
    """Write a minimal pyproject.toml next to the app so uv can sync it."""
    project_dir = (project_dir or requirements.parent).resolve()
    deps, skipped = parse_requirements(requirements)
    name = _project_name(project_dir)
    dep_lines = "".join(f'    "{d}",\n' for d in deps)
    body = (
        f"{GENERATED_MARKER}\n"
        "# 手動で作られたものではありません。依存やエントリが不足する場合があります。\n"
        "[project]\n"
        f'name = "{name}"\n'
        'version = "0.0.0"\n'
        f'requires-python = "{_detect_requires_python(project_dir)}"\n'
        "dependencies = [\n"
        f"{dep_lines}"
        "]\n"
    )
    target = project_dir / "pyproject.toml"
    target.write_text(body, encoding="utf-8")
    return ConversionResult(
        pyproject=target,
        dependencies=deps,
        skipped=skipped,
        sources=[requirements],
    )
